spring.application.name=slideshowtraveldestinatinos

spring.data.mongodb.uri=mongodb+srv://DatabaseAdmin:DaTabAs3pAs$w0rD@slideshowcluster.4o9i0tf.mongodb.net/?retryWrites=true&w=majority&appName=SlideShowCluster
spring.data.mongodb.database=SlideShowDB
